name: Run action and validate environment

on: [push]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Run Action
        run: export INPUT_MINIKUBE_VERSION="v1.5.2" && export INPUT_KUBERNETES_VERSION="v1.17.2" && export INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN  }} && node src/index.js
      - name: Validate Minikube
        run: minikube status
      - name: Validate Cluster
        run: kubectl get nodes
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
#      - name: Enable Hyper-V
#        run: DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V /Quiet
      - name: Enable Hyper-V
        shell: powershell
        run: |
          Enable-WindowsOptionalFeature -Online -FeatureName "Microsoft-Hyper-V" -NoRestart -All
          Restart-Computer -Force
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Run Action
        shell: cmd
        run: |
          set INPUT_MINIKUBE_VERSION=v1.5.2
          set INPUT_KUBERNETES_VERSION=v1.17.2
          set INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN  }}
          node src\index.js
#      - name: Validate Minikube
#        run: minikube status
#      - name: Validate Cluster
#        run: kubectl get nodes
